name: Update Latest Blog Posts

on:
  schedule:
    # Run daily at 6:00 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-blog-posts:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://phiptech.com/feed/"